---
environments:
  poc: {}
---
repositories:
  - name: netbox
    url: https://charts.netbox.oss.netboxlabs.com

releases:
  - name: netbox
    namespace: netbox
    chart: netbox/netbox
    version: 6.0.2
    values:
      - values/base.yaml
      - values/{{ .Environment.Name }}.yaml
